export interface JobVacancyResDto {
  vacancyId: string;
  vacancyCode: string;
  vacancyTitle: string;
  hrId: string;
  hrName: string;
  userId: string;
  userName: string;
  startDate: string;
  endDate: string;
  levelId: string
  levelName: string;
  statusId: string;
  statusName: string;
  companyName: string;
  companyPhotoId: string;
  companyDesc: string;
  degreeId: string;
  degreeName: string;
  genderId: string;
  genderName: string;
  ageVacancyId: string;
  ageVacancyName: string;
  jobTypeId: string;
  jobTypeName: string;
  salary: string;
  cityId: string;
  cityName: string;
  address: string;
  description: string;
}
